# Generated by Django 4.2.3 on 2023-07-15 11:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import webapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to='images/', verbose_name='Property image')),
                ('name', models.CharField(help_text='Enter building / society name', max_length=200)),
                ('area', models.CharField(help_text='Ex : Wakad, Hinjewadi...', max_length=200)),
                ('city', models.CharField(choices=[('Pune', 'Pune')], default='Pune', max_length=15)),
                ('property_type', models.CharField(choices=[('Flat', 'Flat'), ('House', 'House'), ('Flatmate', 'Flatmate'), ('Shop', 'Shop'), ('Office', 'Office')], default='Flat', max_length=15)),
                ('bhk_type', models.CharField(choices=[('1 RK', 'RK'), ('1 BHK', '1 BHK'), ('2 BHK', '2 BHK'), ('2.5 BHK', '2.5 BHK'), ('3 BHK', '3 BHK')], default='1 BHK', max_length=15)),
                ('list_type', models.CharField(choices=[('Rent', 'Rent'), ('Sale', 'Sale')], default='Rent', max_length=15)),
                ('description', models.TextField(help_text='Enter detailed description like amenities, preferences, etc', max_length=10000)),
                ('rent', models.PositiveBigIntegerField()),
                ('deposit', models.PositiveBigIntegerField()),
                ('available_from', models.DateField(default=datetime.date.today)),
                ('owner_name', models.CharField(max_length=200)),
                ('ph_contact', models.CharField(max_length=12)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('approver', models.ForeignKey(on_delete=models.SET(webapp.models.get_sentinel_user), related_name='approver', to=settings.AUTH_USER_MODEL)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
