# Generated by Django 4.2.3 on 2023-07-16 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0002_remove_property_image_alter_property_approver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='publisher',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to=settings.AUTH_USER_MODEL),
        ),
    ]
