# Generated by Django 4.2.3 on 2023-07-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_property_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
